config/routes.rb
Dish::Application.routes.draw do
  constraints(:id => /[^\/]+/) do
    resources :hosts do
      get 'auto_complete_search', :on => :collection
    end
    resources :packages do
      get 'auto_complete_search', :on => :collection
    end
  end

  match '/' => 'packages#index'
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many :muxes, :dependent => :destroy
  has_many :packages, :through => :muxes, :uniq => true
  has_one :os, :through => :muxes
  validates_uniqueness_of :name

  scoped_search :on => :name, :complete_value => :true, :default_order => true
  scoped_search :in => :packages, :on => :name, :complete_value => :true, :rename => "package", :only_explicit => true
  scoped_search :in => :os,       :on => :name,  :complete_value => :true, :rename => "os", :only_explicit => true

  def to_s
    name
  end

  def to_param
    name
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_filter :verify_authenticity_token, :except => :create

  def index
    @hosts = Host.search_for(params[:search], :order => params[:order]).paginate(:page => params[:page])
    @counter = Host.count(:conditions => {:id => @hosts.map(&:id)}, :group => :host_id, :joins => :muxes)
  end

  def show
    @host = Host.find_by_name(params[:id])
    @muxes = Mux.where(:host_id => @host).includes([:package, :version, :arch]).order("packages.name ASC").paginate(:page => params[:page])
  end

  def new
    @host = Host.new
  end

  def create
    @host = Host.new(params[:host])
    if @host.save
      flash[:notice] = "Successfully created host."
      redirect_to @host
    else
      render :action => 'new'
    end
    Mux.delay.import(@host.name, params[:os], params[:packagelist]) if params[:script]
  end

  def edit
    @host = Host.find_by_name(params[:id])
  end

  def update
    @host = Host.find_by_name(params[:id])
    if @host.update_attributes(params[:host])
      flash[:notice] = "Successfully updated host."
      redirect_to @host
    else
      render :action => 'edit'
    end
  end

  def destroy
    @host = Host.find_by_name(params[:id])
    @host.destroy
    flash[:notice] = "Successfully destroyed host."
    redirect_to hosts_url
  end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_for @host do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/hosts/edit.html.erb
<% title "Edit Host" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @host %> |
  <%= link_to "View All", hosts_path %>
</p>

app/views/hosts/index.html.erb
<% title "Hosts" %>
<%= render 'common/search' %>

<table>
  <tr>
    <th><%= sort :name %></th>
    <th><%= sort :os %></th>
    <th>Package Count</th>
    <th>Last Update<th>
    <th></th>
  </tr>
  <% for host in @hosts %>
    <tr>
      <td><%= link_to host.name, host %></td>
      <td><%= host.os %></td>
      <td><%= @counter[host.id] || @counter[host.id.to_s] %></td>
      <td><%= time_ago_in_words host.updated_at %></td>
      <td>
        <%= link_to "Destroy", host, :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

<%= page_entries_info @hosts %>
<%= will_paginate @hosts %>
<p><%= link_to "New Host", new_host_path %></p>

app/views/hosts/new.html.erb
<% title "New Host" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", hosts_path %></p>

app/views/hosts/show.html.erb
<% title "#{h @host.name} (#{@muxes.first.try(:os)})" %>
<table>
  <tr>
    <th>Package</th>
    <th>Version</th>
    <th>Arch</th>
    <th>Last changed</th>
  </tr>
  <% for mux in @muxes -%>
    <tr>
      <td><%= link_to mux.package, package_path(mux.package) %></td>
      <td><%= mux.version %></td>
      <td><%= mux.arch %></td>
      <td><%= time_ago_in_words mux.updated_at %></td>
    </tr>
  <% end -%>
</table>
<%= page_entries_info @muxes, :entry_name => "packages" %>
<%= will_paginate @muxes %>

<p>
<%= link_to "View All", hosts_path %>
<span class="pagination">last updated <%= time_ago_in_words @host.updated_at %> ago</span>
</p>